# -*- coding: utf-8 -*-
"""Controle da Tv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ulmqfoVPiURT_6sot2c4GRkPNlf9PCAl
"""

class TV:
    def __init__(self, channel, volume, previous_volume):
        self.channel = channel
        self.volume = volume
        self.previous_volume = previous_volume
    
    def set_channel(self, channel):
        if 0 <= channel <= 100:
            self.channel = channel
        else:
            print("Canal inválido.")
    
    def increase_volume(self, volume):
        if self.volume + volume <= 100:
            self.volume += volume
        else:
            print("Volume máximo atingido.")
    
    def decrease_volume(self, volume):
        if self.volume - volume >= 0:
            self.volume -= volume
        else:
            print("Volume mínimo atingido.")
    
    def mute(self):
        if self.volume > 0:
            self.previous_volume = self.volume
            self.volume = 0
        else:
            self.volume = self.previous_volume

# teste da classe
tv = TV(0, 50, 50)
while True:
    print("Escolha uma opção:")
    print("1. Mudar de canal")
    print("2. Aumentar volume")
    print("3. Diminuir volume")
    print("4. Mute")
    print("5. Sair")
    escolha = input("Sua escolha: ")

    if escolha == "1":
        canal = int(input("Insira o número do canal: "))
        tv.set_channel(canal)
        print("Canal atual:", tv.channel)
    elif escolha == "2":
        volume = int(input("Insira o número de unidades a aumentar o volume: "))
        tv.increase_volume(volume)
        print("Volume atual:", tv.volume)
    elif escolha == "3":
        volume = int(input("Insira o número de unidades a diminuir o volume: "))
        tv.decrease_volume(volume)
        print("Volume atual:", tv.volume)
    elif escolha == "4":
        tv.mute()
        print("Volume atual:", tv.volume)
    elif escolha == "5":
        break
    else:
        print("Opção inválida, tente novamente.")

"""faca uma classe que simule um controle de tv
o usuariuo deve ser capaz de informar o numero do canal e aumentar ou diminuir o volume
certifique se que o canal e o volume estejam sempre dentro dafaixa valida (0 -1090)
fazer o metodo mute( ao ser chamado, zera o volume, caso o volume ja esteja zerado, retoma o volume anterior.
"""