# -*- coding: utf-8 -*-
"""Containvestimento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1NYAfJc6REv9-kYO8qE2XB7cCZg95Wb
"""

class ContaInvestimento:
    def __init__(self, num,nome,saldo,taxa):
        self.numConta = num
        self.nome = nome
        self.saldo = 0
        self.taxaJuros = taxa

    def sacar(self,saldo):
         if self.saldo >= saldo:
           self.saldo -= saldo 
         else: 
            print(f"{self.nome} Seu saldo é negativo.")
 
    def depositar(self,saldo):
        self.saldo += saldo 

    def adicioneJuros(self):
        self.saldo += self.saldo * self.taxaJuros/100

c = ContaInvestimento("87654", "Fulano",10,1000)

#teste de Classe

c.depositar(1000)
#c.sacar(0)
print(c.saldo)
c.adicioneJuros()
print(c.saldo)