# -*- coding: utf-8 -*-
"""Ex_aumenta_Salário.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GIJAdgQaerup_NzLWIaUc-5dEeKmQ1vg
"""

class Funcionario():
    def __init__(self, n, s):
        self.nome = n
        self.salario = s

    def getNome(self):
        return self.nome

    def getSalario(self):
        return self.salario

    def aumentarSalario(self, percentual):
        aumento = self.salario * (percentual/100)
        self.salario = self.salario + aumento

#teste de classe 
nome = input("digite o nome do funcionario : ")
salario =float(input("digite o salario : "))
fun = Funcionario(nome,salario)
percentual = float(input("digite o percentual de aumento : "))
fun.aumentarSalario(percentual)
print(fun.getSalario())