# -*- coding: utf-8 -*-
"""experimento do macaco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-2RsjxkbPJzjI0nfFFR91HamsiaNOtm
"""

class Macaco:
    def __init__(self, nome):
        self.nome = nome
        self.estomago = []

    def comer(self, alimento):
        self.estomago.append(alimento)
        print(f"{self.nome} comeu {alimento}.")

    def verEstomago(self):
        print(f"O estômago de {self.nome} contém: {self.estomago}")

    def digerir(self):
        if len(self.estomago) > 0:
            self.estomago.pop(0)
            print(f"{self.nome} digeriu o alimento.")
        else:
            print(f"{self.nome} não tem comida para digerir.")

def alimentar_macaco(macaco):
    lanche = input("Qual é o café da manhã? ")
    macaco.comer(lanche)
    almoco = input("O que tem para o almoço? ")
    macaco.comer(almoco)
    janta = input("O que tem para o jantar? ")
    macaco.comer(janta)

try:
    nome_macaco1 = input("Insira o nome do primeiro macaco: ")
    nome_macaco2 = input("Insira o nome do segundo macaco: ")
    macaco1 = Macaco(nome_macaco1)
    macaco2 = Macaco(nome_macaco2)
    
    while True:
        print("Escolha um macaco para alimentar:")
        print("1.", macaco1.nome)
        print("2.", macaco2.nome)
        print("3. Ver estômago")
        print("4. Digerir alimento")
        print("5. Sair")
        escolha = input("Sua escolha: ")

        if escolha == "1":
            alimentar_macaco(macaco1)
        elif escolha == "2":
            alimentar_macaco(macaco2)
        elif escolha == "3":
            macaco1.verEstomago()
            macaco2.verEstomago()
        elif escolha == "4":
            macaco1.digerir()
            macaco2.digerir()
        elif escolha == "5":
            break
            
        else:
            print("Escolha inválida, tente novamente.")
except ValueError:
    print("Entrada inválida, por favor insira um número válido.")