# -*- coding: utf-8 -*-
"""Cópia de Lógica de Programação 2022.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18LZxkVKxngkn2778hVN7WISCTlDpuelS
"""

#Tipos primitivos de dados

int() = inteiros(9, 6, -4)
float() = reais(9.8, 5.6, 3.4)
str() = texto ("27", "texto", "2.9", ".-+")
bool() = lógicos True ou False

print("Olá Mundo") #Mostrando um texto
idade = 26 #Criando uma variavel e salvando o valor 26 nela
print(idade) #Mostrando uma variavel
print("A minha idade é", idade) #Mostrando um texto e uma variavel

print("Qual seu ano de nascimento?") #pedindo uma informação ao usuário
ano = int(input()) #Convertendo o que foi digitado pelo usuário para inteiro e em seguida salvando na variavel 'ano'
idade = 2022 - ano #criando uma variavel e salvando nela o resultado de um calculo
print("Sua idade é", idade) #Mostrando um texto e uma variavel

print("Qual a temperatura atual em sua casa?") #pedindo uma informação ao usuário
temp = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel 'temp'
print("A temperatura é" ,temp) #Mostrando um texto e uma variavel

print("Digite o valor da base") #pedindo uma informação ao usuário
base = int(input()) #Convertendo o que foi digitado pelo usuário para inteiro e em seguida salvando na variavel
print("Digite o valor do expoente") #pedindo uma informação ao usuário
expoente = int(input()) #Convertendo o que foi digitado pelo usuário para inteiro e em seguida salvando na variavel
resultado = base ** expoente #calculando a potencia e salvando na variavel resultado
print("O resultado é", resultado) #Mostrando o resultado do calculo

print("Digite a primeira nota") #pedindo uma informação ao usuário
nota1 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
print("Digite a segunda nota") #pedindo uma informação ao usuário
nota2 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
media = (nota1 + nota2)/2 #calculando a média das notas e salvando na variavel media
print("A média foi: %.2f" % media) #mostrando a media com apenas 2 casas decimais

"""Estruturas condicionais"""

print("Digite a primeira nota") #pedindo uma informação ao usuário
nota1 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
print("Digite a segunda nota") #pedindo uma informação ao usuário
nota2 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
media = (nota1 + nota2)/2 #calculando a média das notas e salvando na variavel media
print("A média foi: %.2f" % media) #mostrando a media com apenas 2 casas decimais
if media >= 7: #verificando se a média é maior ou igual a 7
  print("O aluno foi aprovado") #caso seja, o aluno é aprovado
else: #caso contrário, ou seja, média menor do que 7
  print("O aluno foi reprovado") #o aluno é reprovado

print("Digite a primeira nota") #pedindo uma informação ao usuário
nota1 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
print("Digite a segunda nota") #pedindo uma informação ao usuário
nota2 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
media = (nota1 + nota2)/2 #calculando a média das notas e salvando na variavel media
print("A média foi: %.2f" % media) #mostrando a media com apenas 2 casas decimais
if media >= 7: #verificando se a média é maior ou igual a 7
  print("O aluno foi aprovado") #caso seja, o aluno é aprovado
elif media >= 5: #se a média for menor do que 7, verificamos se ela é maior ou igual a 5
  print("O aluno está na recuperação") #caso seja, o aluno está na recuperação
else: #caso contrário, ou seja, média menor do que 5
  print("O aluno foi reprovado") #o aluno é reprovado

print("Digite a primeira nota") #pedindo uma informação ao usuário
nota1 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
print("Digite a segunda nota") #pedindo uma informação ao usuário
nota2 = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
media = (nota1 + nota2)/2 #calculando a média das notas e salvando na variavel media
print("A média foi: %.2f" % media) #mostrando a media com apenas 2 casas decimais
if media >= 7: #verificando se a média é maior ou igual a 7
  print("O aluno foi aprovado") #caso seja, o aluno é aprovado
elif media >= 5: #se a média for menor do que 7, verificamos se ela é maior ou igual a 5
  print("Digite a nota da prova de recuperação") #caso seja, o aluno está na recuperação e pediremos a nota da recuperação
  rec = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
  if rec >= 5: #verificando a nota na recuperação for maior ou igual a 5 
    print("O aluno foi aprovado na recuperação") #caso seja, o aluno é aprovado na recuperação
  else: #caso contrário, ou seja, nota na recuperação menor do que 5
    print("O aluno foi reprovado na recuperação") #o aluno é reprovado na recuperação
else: #caso contrário, ou seja, média menor do que 5
  print("O aluno foi reprovado") #o aluno é reprovado

"""Desenvolva um sistema que mostre a desvalorização de carros usados, caso o ano de fabricação seja 2006 ou anterior, a desvalorização será de 12%. Caso contrário, a desvalorização será de 7%"""

print("Digite o valor do carro") #pedindo uma informação ao usuário
valor = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
print("Digite o ano de fabricação") #pedindo uma informação ao usuário
ano = int(input()) #Convertendo o que foi digitado pelo usuário para inteiro e em seguida salvando na variavel
if ano <= 2006: #verificando se o ano de fabricação do carro é anterior a 2006, se for, a desvalorização será de 12%
  resultado = valor - valor * 0.12 #desvalorização = valor * 0.12, ou seja, 12% do valor do veiculo. novoValor = valor - desvalorização
else: #caso contrário, a desvalorização será de 7%
  resultado = valor - valor * 0.07 #desvalorização = valor * 0.07, ou seja, 7% do valor do veiculo. novoValor = valor - desvalorização
print("O valor atual do carro é:", resultado) #mostrando o novo valor do veiculo

"""Um posto está vendendo combustíveis com a seguinte tabela de descontos:
Até 20 litros, desconto de 3% por litro Álcool;Acima de 20 litros, desconto de 5% por litro;Até 20 litros, desconto de 4% por litro de Gasolina;Acima de 20 litros, desconto de 6% por litro. Escreva um algoritmo que leia o número de litros vendidos e o tipo de combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser pago pelo cliente sabendo-se que o preço do litro da gasolina é 7.90 e o preço do litro do álcool é 5.30.
"""

print("Digite A para alcool e G para gasolina") #pedindo uma informação ao usuário
codigo = input() #salvando o que foi digitado pelo usuário na variavel
if codigo == "A" or codigo == "G": #verificando se o que foi digitado é válido, se for, damos prosseguimento
  if codigo == "A": #verificando se o usuário escolheu a opção alcool
    print("Quantos litros de alcool deseja abastecer?") #pedindo uma informação ao usuário
    qtd = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
    if qtd > 0 and qtd <= 20: #verificando se a quantidade de litros que o usuário pediu está até 20 litros
      desconto = 5.30 * 0.03 #desconto = valor * 0.03, ou seja, 3% do valor do litro
    else: #caso contrário, ou seja, se a quantidade de litros que o usuário pediu foi acima de 20 litros
      desconto = 5.30 * 0.05 #desconto = valor * 0.05, ou seja, 5% do valor do litro
    alcool = 5.30 - desconto #novoValor = valor - desconto
    total = alcool * qtd #total a pagar = novoValor * quantidade de litros
  else: #caso contrário, ou seja, se o usuário escolheu a opção gasolina
    print("Quantos litros de gasolina deseja abastecer?") #pedindo uma informação ao usuário
    qtd = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
    if qtd > 0 and qtd <= 20: #verificando se a quantidade de litros que o usuário pediu está até 20 litros
      desconto = 7.90 * 0.04 #desconto = valor * 0.04, ou seja, 4% do valor do litro
    else: #caso contrário, ou seja, se a quantidade de litros que o usuário pediu foi acima de 20 litros
      desconto = 7.90 * 0.06 #desconto = valor * 0.06, ou seja, 6% do valor do litro
    gasolina = 7.90 - desconto #novoValor = valor - desconto
    total = gasolina * qtd #total a pagar = novoValor * quantidade de litros
  print("O total a pagar é:", total) #Mostrando o total a pagar
else: #caso tenha sido digitado um código inválido
  print("Código inválido") #informando ao usuário

"""Estruturas de Repetição: FOR"""

soma = 0 #criamos a variavel com valor zero
for i in range(4): #o que estiver abaixo será realizado 4 vezes
  print("Digite a nota do aluno") #pedindo uma informação ao usuário
  nota = float(input()) #Convertendo o que foi digitado pelo usuário para real e em seguida salvando na variavel
  soma = soma + nota #somando a nota digitada com o valor anterior presente na variavel soma e salvando esse resultado na própria variavel
media = soma / 4 #após obter a soma das 4 notas, divide a soma por 4 para encontrar a média
print("A média é: %.2f" % media) #mostrando o resultado

"""Desenvolva um programa para calcular a potência de uma base e um expoente inseridos pelo usuário sem usar a função de potência do python."""

mult = 1 #criamos a variavel com valor um, pois ela será usada numa multiplicação e não queremos que seu valor afete o calculo
print("Digite o valor da base") #pedindo uma informação ao usuário
base = int(input()) #Convertendo o que foi digitado pelo usuário para inteiro e em seguida salvando na variavel
print("Digite o valor do expoente") #pedindo uma informação ao usuário
expoente = int(input()) #Convertendo o que foi digitado pelo usuário para inteiro e em seguida salvando na variavel
for i in range(expoente): #o que estiver abaixo será realizado pela quantidade vezes correspondente ao expoente digitado pelo usuário
  mult = mult * base #multiplicando a base com o valor anterior presente na variavel mult
print(mult) #mostrando o resultado

"""Faça um sistema que pergunte ao usuário quantas pessoas tem numa turma e repita para essa quantidade de pessoas a seguinte pergunta "qual a sua idade?".
Depois que todos digitarem suas idades, faça uma média da idade da turma e diga se a turma é jovem (media <=25), adulta (entre 25 e 60) ou idosa (acima de 60).
"""

print("Digite a quantidade de pessoas na turma")
total = int(input())
soma = 0
for i in range(total):
  print("Qual a sua idade?")
  idade = int(input())
  soma = soma + idade
media = soma / total
if media <= 25:
  print("A turma é jovem")
elif media <= 60:
  print("A turma é adulta")
else:
  print("A turma é idosa")

"""Numa eleição existem três candidatos. Faça um sistema que peça o número total de eleitores que irão votar. Peça para cada eleitor votar e ao final mostre o número de votos de cada candidato e o candidato que venceu a eleição, caso haja empate entre os três candidatos, informe isso, caso haja empate entre dois candidatos, informe que eles irão para o segundo turno."""

voto1 = 0
voto2 = 0
voto3 = 0
print("digite a quantidade de eleitores")
qtd =  int(input())
for i in range(qtd):
  print('''Digite em qual candidato deseja votar:
  1 para o candidato1,
  2 para candidato2,
  3 para candidato3''')
  voto = int(input())
  if voto == 1:
    voto1 += 1
  elif voto == 2:
    voto2 += 1
  elif voto == 3:
    voto3 += 1
  else:
    print("Voto nulo")
if voto1 > voto2 and voto1 > voto3:
  print("Candidato 1 venceu")
elif voto2 > voto1 and voto2 > voto3:
  print("Candidato 2 venceu")
elif voto3 > voto1 and voto3 > voto2:
  print("Candidato 3 venceu")
elif voto1 == voto2 and voto1 == voto3:
  print("Os candidatos empataram")
elif voto1 == voto2 and voto1 > voto3:
  print("candidatos 1 e 2 vão para o segundo turno")
elif voto1 == voto3 and voto1 > voto2:
  print("candidatos 1 e 3 vão para o segundo turno")
elif voto2 == voto3 and voto2 > voto1:
  print("candidatos 2 e 3 vão para o segundo turno")

"""Desenvolva um sistema que peça ao usuário para digitar 10 caracteres e ao final diga quantos caracteres são números e quantos são letras


OBS: para verificar se um caracter é uma letra faça **if variavel.isalpha():**
para verificar se um caracter é um número faça **if variavel.isdigit():**


"""

qtdLetras = 0
qtdNumeros = 0
for i in range(10):
  print("Digite um caracter")
  valor = input()
  if valor.isalpha():
    qtdLetras += 1
  elif valor.isdigit():
    qtdNumeros += 1
print("A quantidade de letras foi", qtdLetras)
print("A quantidade de números foi", qtdNumeros)

"""Estruturas de Repetição: While"""

num = 2
while num != 0:
  print("Digite um número")
  num = int(input())

print("Digite o numero que deseja saber o fatorial")
num = int(input())
resultado = num

while num != 1:
  resultado = resultado * (num-1)
  num -= 1
print("O fatorial é", resultado)

"""Suponha que um país A tem população de 80000 e uma taxa de crescimento anual de 3%. E que um país B tem população de 200000 e uma taxa de crescimento anual de 1,5%. Quantos tempos levará para a população do país A alcançar ou ultrapassar a população do país B?"""

paisA = 80000
paisB = 200000
taxaA = 1.03
taxaB = 1.015
ano = 0

while paisA < paisB:
  paisA = paisA * taxaA
  paisB = paisB * taxaB
  ano += 1
print("Levará", ano, "anos para A alcançar B")

"""Desenvolva um programa para calcular a soma e a média de n números inteiros inseridos pelo usuário. Digite 0 para terminar."""

soma = 0
media = 0
count = 0
num = ""

while num != 0:
  print("Digite um número")
  num = int(input())
  soma = soma + num
  count += 1
media = soma / (count-1)
print("A soma é", soma)
print("A média é", media)

"""Desenvolva um programa para dizer o maior e o menor de n números inteiros inseridos pelo usuário que estejam no intervalo entre 0 e 999999. Digite -1 para terminar."""

num = 0
maior = 0
menor = 999999
while num != -1:
  num = float(input())
  if num > maior and num <= 999999:
    maior = num
  if num < menor and num >= 0:
    menor = num
print("O maior número é", maior)
print("O menor número é", menor)

"""Funções"""

def hello (meuNome):
  print("Olá", meuNome)

hello("Ícaro")

def calculaMedia (nota1, nota2, nota3, nota4):
  print("AQUI OCORRE O DESVIO")
  media = (nota1+nota2+nota3+nota4)/4
  return media

print("AQUI COMEÇA O FLUXO PRINCIPAL")
print("Digite as notas")
notaPrimeira = float(input())
notaSegunda = float(input())
notaTerceira = float(input())
notaQuarta = float(input())
mediaNota = calculaMedia(notaPrimeira, notaSegunda, notaTerceira, notaQuarta)
print("AQUI RETORNAMOS AO FLUXO PRINCIPAL")
if mediaNota >= 7:
  print("Aprovado")
else:
  print("Reprovado")

"""Faça um programa com uma função que receba um número e retorne o caractere P se o numero for positivo e N se o número for zero ou negativo"""

def analisaNumero(numero):
  if numero > 0:
    return 'P'
  else:
    return 'N'

print("Digite um número")
valor = float(input())
resultado = analisaNumero(valor)
if resultado == 'P':
  print("O número é positivo")
elif resultado == 'N':
  print("O número é negativo ou zero")

"""Faça um programa, com uma função chamada somaImposto. A função possui 2 parametros: taxaImposto e custo.

taxaImposto é a quantia de imposto sobre vendas expressa em porcentagem

custo é o custo de um item antes do imposto

A função irá alterar o valor do custo, aplicando o imposto.
"""

def somaImposto(custo, taxaImposto):
  novoCusto = custo + (custo * taxaImposto / 100)
  return novoCusto

print("Digite o custo do produto")
produto = float(input())
print("Digite o imposto que será aplicado")
imposto = float(input())
resultado = somaImposto(produto, imposto)
print("O novo custo do produto é", resultado)

"""Faça um programa que use a função valorPagamento para determinar o valor a ser pago por uma prestação de uma conta. O programa deverá solicitar ao usuário o valor da prestação e o número de dias em atraso e passar estes valores para a função valorPagamento, que calculará o valor a ser pago e devolverá este valor ao programa que a chamou. O programa deverá então exibir o valor a ser pago na tela. Após a execução o programa deverá voltar a pedir outro valor de prestação e assim continuar até que seja informado um valor igual a zero para a prestação. Neste momento o programa deverá ser encerrado. O cálculo do valor a ser pago é feito da seguinte forma. Para pagamentos sem atraso, cobrar o valor da prestação. Quando houver atraso, cobrar 3% de multa, mais 0,1% de juros por dia de atraso."""

def valorPagamento(valor, dias):
  if dias > 0:
    valorFinal = valor + (valor * 0.03)
    juros = valor * 0.001 * dias
    return valorFinal + juros
  else:
    return valor

parcela = ""
while True:
  print("Digite o valor da parcela")
  parcela = float(input())
  if parcela == 0:
    break
  else:
    print("Digite a quantidade de dias de atraso")
    atraso = int(input())
    resultado = valorPagamento(parcela, atraso)
    print("O valor da parcela com atraso é %.2f" % resultado)

def valorPagamento(valor, dias):
  if dias > 0:
    valorFinal = valor + (valor * 0.03)
    juros = valor * 0.001 * dias
    return valorFinal + juros
  else:
    return valor

parcela = ""
while parcela != 0:
  print("Digite o valor da parcela")
  parcela = float(input())
  if parcela != 0:
    print("Digite a quantidade de dias de atraso")
    atraso = int(input())
    resultado = valorPagamento(parcela, atraso)
    print("O valor da parcela com atraso é %.2f" % resultado)

"""Usando função, faça um programa que implemente um jogo de Dados. 
O jogador lança um par de dados, obtendo um valor entre 2 e 12. Se, na primeira jogada, você tirar 7 ou 11, você ganhou. Se você tirar 2, 3 ou 12 na primeira jogada, você perdeu. Se, na primeira jogada, você fez um 4, 5, 6, 8, 9 ou 10, este é seu "Ponto". Seu objetivo agora é continuar jogando os dados até tirar este número novamente. Você perde, no entanto, se tirar um 7 antes de tirar este Ponto novamente.

"""

import random

def jogaDados():
  jogada = random.randint(2, 12)
  return jogada

qtdJogadas = 1
ponto = 0
while True:
  jogada = jogaDados()
  print("Jogada %i: %i" % (qtdJogadas, jogada))
  if(qtdJogadas == 1):
    if(jogada == 2) or (jogada == 3) or (jogada == 12):
      print("Você perdeu")
      break
    elif (jogada == 7) or (jogada == 11):
      print("Você venceu")
      break
    else:
      ponto = jogada
      print("Seu ponto é:", ponto)
  else:
    if jogada == 7:
      print("Você perdeu")
      break
    elif jogada == ponto:
      print("Você venceu")
      break
  qtdJogadas += 1

"""Faça uma função que receba um texto e uma letra e informe quantas vezes a letra aparece no texto

OBS: use a função count

*texto.count(letra)*
"""

def contaLetra(texto, letra):
  qtd = texto.count(letra)
  return qtd

print("Digite um texto")
tex = input()
print("Digite uma letra")
let = input()
resultado = contaLetra(tex, let)
print("A letra %s aparece: %i vezes" % (let, resultado))

"""Faça uma função que informe a quantidade de digitos de um determinado número inteiro informado.
OBS: o comando len(algumaCoisa) dirá o tamanho da variavel algumaCoisa
"""

def contaDigitos(numero):
  qtd = len(numero)
  return qtd

print("Digite um número inteiro")
num = input()
resultado = contaDigitos(num)
print("O número %s possui %i digitos" % (num, resultado))

"""Funções Recursivas"""

def contagemRegressiva(n):
  while(n):
    print(n)
    n -= 1
  print("Decolar!")

contagemRegressiva(5)

def contagemRegressiva(n):
  if n == 0:
    print("Decolar!")
  else:
    print(n)
    contagemRegressiva(n-1)

contagemRegressiva(5)

def fatorial(numero):
  resultado = 1

  for i in range(1, numero+1):
    resultado = resultado * i

  return resultado

fatorial(5)

def fatorial(numero):
  if numero < 2:
    return 1

  return numero * fatorial(numero - 1)

fatorial(5)

def infinita(numero):
  return infinita(numero - 1)

infinita(100)

"""Faça um programa, que lê um número n e imprime os n primeiros números da sequência de Fibonacci."""

print("Digite quantos números da sequência deseja")
num = int(input())
A = 0
B = 1
contador = 0
while contador < num:
  print(A)
  C = A + B
  A = B
  B = C
  contador+=1

def fibonacci(n):
  if n < 1:
    return 0
  elif n <= 2:
    return 1
  return fibonacci(n-1) + fibonacci(n-2)

print("Digite quantos números da sequência deseja")
num = int(input())
for i in range(num):
  print(fibonacci(i))

"""Crie um programa que calcula o máximo divisor comum entre dois números usando recursão."""

def mdc(num1, num2):
  if num2 != 0:
    return mdc(num2, num1%num2)
  else:
    return num1

print("Digite dois números inteiros positivos")
n1 = int(input())
n2 = int(input())
resultado = mdc(n1, n2)
print("O mdc entre %i e %i é: %i" % (n1, n2, resultado))

"""Escreva uma função recursiva que calcule o valor de A elevado a B"""

def potencia(base, expoente):
  if expoente == 0:
    return 1
  elif expoente > 0:
    return base * potencia(base, expoente-1)
  elif expoente < 0:
    return (1/potencia(base, - expoente))

print("digite a base e o expoente")
a = int(input())
b = int(input())
resultado = potencia(a, b)
print(resultado)

"""Revisão"""

def potencia (expoente, base):
  return base ** expoente

print("Digite a base")
a = int(input())
print("Digite o expoente")
b = int(input())
a = potencia(b, a)
print(potencia(b, a))

"""Questão 1 - Resposta: 100"""

#Questão 2
def somaFracoes(n):
  num = 2
  den = 3
  count = n - 1
  soma = 0
  while count > 0:
    soma += num/den
    num += 1
    den += 2
    count -= 1
  return soma

n = -1
while n < 0:
  print("Digite um número inteiro positivo")
  n = int(input())
resultado = somaFracoes(n)
print(resultado)

#Questão 3
def saida(hora, minuto, letra):
  print("%i:%i %s.M." % (hora, minuto, letra))

def conversao(hora, minuto):
  if hora > 12:
    hora -= 12
    saida(hora, minuto, "P")
  else:
    saida(hora, minuto, "A")
while(True):
  print("Digite a hora")
  h = int(input())
  print("Digite os minutos")
  m = int(input())
  conversao(h, m)
  print("Digite uma letra para parar")
  letra = input()
  if letra.isalpha():
    break

"""Resolução da prova de funções"""

#Questão 01
def imprimeMaior(a, b):
  if a > b:
    return a
  elif b > a:
    return b
  else:
    return "Os números são iguais"

print("Digite o valor A")
valorA = float(input())
print("Digite o valor B")
valorB = float(input())
print(imprimeMaior(valorA,valorB))

#Questão 02
def maiorQueLimite(a, b, limite):
  if a > limite and b > limite:
    return 2
  elif a > limite or b > limite:
    return 1
  else:
    return 0

print("Digite o valor A")
valorA = float(input())
print("Digite o valor B")
valorB = float(input())
print("Digite o limite")
valorLimite = float(input())
print(maiorQueLimite(valorA, valorB, valorLimite))

#Questão 03
def somaNum(num):
  if(num == 1):
    return 1
  else:
    return num + somaNum(num - 1)

print("Digite o valor de N")
numero = int(input())
print(somaNum(numero))

#Questão 04
def C_para_F(C):
  F = (C*9/5) + 32
  return F

def F_para_C(F):
  C = (F-32)*5/9
  return C

print('''Digite 1 para converter de Celsius para Farenheit
Digite 2 para conveter de Farenheit para Celsius''')
escolha = int(input())
print("Digite a temperatura")
temp = float(input())
if escolha == 1:
  print("A temperatura em farenheit é", C_para_F(temp))
elif escolha == 2:
  print("A temperatura em celsius é", F_para_C(temp))
else:
  print("Tá trollando")

#Questão 05
def maior(x, y, z):
  max = x
  if y > max:
    max = y
  if z > max:
    max = z

  return max

def menor(x, y, z):
  min = x
  if y < min:
    min = y
  if z < min:
    min = z

  return min

print("Digite o valor 1")
valorX = float(input())
print("Digite o valor 2")
valorY = float(input())
print("Digite o valor 3")
valorZ = float(input())
print("O maior número é", maior(valorX, valorY, valorZ))
print("O menor número é", menor(valorX, valorY, valorZ))

#Questão 06
import random
def jogar():
  return random.randint(1, 6)

def repeteJogada(n):
  test1 = 0
  test2 = 0
  test3 = 0
  test4 = 0
  test5 = 0
  test6 = 0
  for i in range(n):
    test = jogar()
    if test == 1:
      test1 += 1
    elif test == 2:
      test2 += 1
    elif test == 3:
      test3 += 1
    elif test == 4:
      test4 += 1
    elif test == 5:
      test5 += 1
    elif test == 6:
      test6 += 1

  print("Número 1 saiu ", test1, " vezes = ",(test1/n)*100, " %")
  print("Número 2 saiu ", test2, " vezes = ",(test2/n)*100, " %")
  print("Número 3 saiu ", test3, " vezes = ",(test3/n)*100, " %")
  print("Número 4 saiu ", test4, " vezes = ",(test4/n)*100, " %")
  print("Número 5 saiu ", test5, " vezes = ",(test5/n)*100, " %")
  print("Número 6 saiu ", test6, " vezes = ",(test6/n)*100, " %")

repeteJogada(1000000)

"""Strings"""

s = "Olá, mundo!"
print(len(s)) #tamanho da string
print("Meu Brasil" + " brasileiro") #concatenação de strings
s1 = s.replace("mundo", "camarada") #substituindo uma parte da string
print(s1)
print(s.startswith("Olá")) #A string começa com 'Olá'?
print(s.endswith("mundo!")) #A string termina com 'mundo!' ?
print(s1.count("a")) #Quantas ocorrências da letra 'a'?

s = "Olá, mundo!"
print(s[0]) #pega posição zero da string
print(s[0:3]) #pega um intervalo correspondente a palavra "Olá"
print(s[-1]) #pega a ultima posição da string
print(s[0], s[-2]) #pega apenas a letra 'O'
print(s[::-1]) #inverte a string
print("u" in s) #verifica se existe a letra 'u' na string
print(s.upper()) #torna a string maiúscula
print(s.lower()) #torna a string minúscula
s = " Olá, mundo! "
print(s)
print(s.strip()) #apaga os espaços do inicio e do fim da string
print(",".join("abc")) #separa a string usando o delimitador indicado

s = "joão silva"
print(s[0:4].capitalize(), s[5:10].capitalize())
# transforma a primeira letra da primeira palavra em maiúscula
a = s.split(" ") #quebra a string em várias substrings onde aparecer o
#delimitador passado, nessa caso " "
print("12345".isdigit()) #verifica se só tem números na string
print("abcde".isalpha()) #verifica se só tem letras na string
print("12345abcde".isalnum()) #verifica se é alfanumerico(apenas letras e números)

S = "Olá Mundo"
for i in range (len(S)):
  print(S[i])

S = "Olá Mundo"
for i in S:
  print(i)

test = "this is just a short string"
test2 = "KEK"
test3 = "This Is A Title"
test4 = " "
print(test.islower()) #verifica se a string é toda minuscula
print(test2.isupper()) #verifica se a string é toda maiuscula
print(test3.istitle()) #verifica se a string é um título (primeira letra de cada palavra maiuscula)
print(test.find("s")) #retorna a posição a da primeira ocorrência do elemento
print(test3.swapcase()) #troca tudo que é maiusculo pra minusculo e vice-versa
print(test4.isspace()) #verifica se uma string contém somente espaços

"""Desenvolva um programa que leia uma string digitada pelo usuário e diga quantos espaços e quantas vogais essa string possui"""

print("Digite uma frase")
frase = input()
espacos = 0
vogais = 0
for i in frase:
  if('AEIOU'.find(i.upper()) >=0):
    vogais += 1
  elif i == " ":
    espacos += 1
print("%i espaços e %i vogais" % (espacos, vogais))

"""Listas"""

frutas = [] #criando uma lista vazia
print(frutas)
frutas.append("laranja") #adicionando um elemento no final da lista
print(frutas)
frutas.append("uva") #adicionando um elemento no final da lista
print(frutas)
frutas.insert(0, "melancia") #adicionando um elemento no inicio da lista
print(frutas)
frutas.remove("laranja") #removendo um item da lista
print(frutas)
frutas.pop(0) #removendo o primeiro item da lista pelo indice
print(frutas)
frutas.clear() #apagar todos os itens da lista
print(frutas)
frutas = ["laranja", "uva", "melancia", "banana"] #criando uma lista preenchida
print(frutas)
print(frutas.index("banana")) #achando a posicão do elemento
frutas.append("laranja")
print(frutas)
print(frutas.count("laranja")) #contando quantas vezes o elemento aparece na lista
print(frutas.index("laranja")) #achando a posicão do elemento
print(frutas.index("laranja", 1)) #achando a posicão do elemento a partir do indice 1
frutas.reverse() #invertendo a ordem dos elementos da lista
print(frutas)
frutas2 = frutas.copy() #copiando os elementos de uma lista para uma nova lista
print(frutas2)
print(frutas[1:4]) #pegando apenas os elementos do indice 1 ao 3
frutas.sort() #ordenando os elementos da lista em ordem alfabética
print(frutas)
frutas.sort(reverse=True) #ordenando os elementos da lista em ordem inversa
print(frutas)

"""Desenvolva um programa que leia 10 números reais, salve-os numa lista e mostre-os na ordem inversa a que foi lida"""

lista = []
for i in range(10):
  num = float(input("Digite um número"))
  lista.append(num)
lista.reverse()
print(lista)

"""Faça um programa que leia 4 notas, adicione-as numa lista, mostre as notas e a média na tela"""

notas = []
for i in range(4):
  nota = float(input("Digite a nota: "))
  notas.append(nota)
print(notas)
soma = 0.0
for i in notas:
  soma += i
print("A média é %.2f:" % (soma/4))

notas = []
soma = 0.0
for i in range(4):
  nota = float(input("Digite a nota: "))
  notas.append(nota)
  soma += notas[i]
print("A média é %.2f:" % (soma/4))

notas = []
for i in range(4):
  nota = float(input("Digite a nota: "))
  notas.append(nota)
soma = sum(notas)
print("A média é %.2f:" % (soma/4))

"""Faça um programa que leia uma lista de 10 caracteres e diga quantas consoantes foram lidas. Imprima as consoates lidas."""

letras = []
vogais = ["A", "E", "I", "O", "U"]

for i in range(10):
  letras.append(input("digite um caracter: ").upper())
consoantes = []
for i in letras:
  if i not in vogais:
    consoantes.append(i)
print(consoantes)
print(len(consoantes))

"""Faça um programa que leia uma lista de 5 números inteiros, mostre a soma, a multiplicação e os números"""

numeros = []
soma = 0
mult = 1
for i in range(5):
  numeros.append(int(input("Digite um número")))
print(numeros)
for i in numeros:
  soma += i
  mult *= i
print(soma)
print(mult)

"""Faça um programa que leia 10 números inteiros e armazene-os numa lista. Armazene os números pares na lista PAR e os números impares na lista IMPAR, imprima as 3 listas."""

numeros = []
par = []
impar = []

for i in range(10):
  numero = int(input("Digite um número"))
  numeros.append(numero)
for i in numeros:
  if i % 2 == 0:
    par.append(i)
  else:
    impar.append(i)
print(numeros)
print(par)
print(impar)

"""Faça um programa que peça as quatro notas de 10 alunos, calcule e armazene numa lista a média de cada aluno, imprima o número de alunos com média maior ou igual a 7,0"""

notas = []
for i in range(2):
  notasAluno = []
  for j in range(4):
    nota = float(input("Informe a nota do aluno %i" % (i+1)))
    notasAluno.append(nota)
  notas.append(notasAluno)

alunosMedia = 0
for notasAluno in notas:
  soma = 0
  for nota in notasAluno:
    soma += nota
  media = soma/4
  if media >= 7:
    alunosMedia +=1
print("%i alunos ficaram com nota igual ou acima da média" % (alunosMedia))

"""Faça um programa que leia duas listas com 10 elementos cada. Gere uma terceira lista de 20 elementos, cujos valores deverão ser compostos pelos elementos intercalados das duas outras listas."""

lista1 = []
lista2 = []
lista3 = []

print("Informe os valores da primeira lista")
for i in range(10):
  lista1.append(int(input("Informe um número")))


print("Informe os valores da segunda lista")
for i in range(10):
  lista2.append(int(input("Informe um número")))

for i in range(10):
  lista3.append(lista1[i])
  lista3.append(lista2[i])

print(lista3)

"""Refaça o programa anterior, agora intercalando 3 listas de 10 elementos cada."""

lista1 = []
lista2 = []
lista3 = []
lista4 = []

print("Informe os valores da primeira lista")
for i in range(10):
  lista1.append(int(input("Informe um número")))

print("Informe os valores da segunda lista")
for i in range(10):
  lista2.append(int(input("Informe um número")))

print("Informe os valores da terceira lista")
for i in range(10):
  lista3.append(int(input("Informe um número")))

for i in range(10):
  lista4.append(lista1[i])
  lista4.append(lista2[i])
  lista4.append(lista3[i])

print(lista4)

"""Revisão

Faça um programa que receba a temperatura média de cada mês do ano e
armazene-as em uma lista. Após isto, calcule a média anual das
temperaturas e mostre todas as temperaturas acima da média anual, e em
que mês elas ocorreram (mostrar o mês por extenso: 1 – Janeiro, 2 –
Fevereiro, . . . ).
"""

meses = ["jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez"]
temperaturas = []
for i in range(12):
  temperaturas.append(float(input("informe a temperatura média do mês de %s:" % meses[i])))

media = sum(temperaturas)/12

for i in range(12):
  if temperaturas[i] > media:
    print("%s - %.2f" % (meses[i], temperaturas[i]))

"""Faça um programa que leia os modelos de cinco carros e armazene-os numa
lista (exemplo de modelos: FUSCA, GOL, VECTRA etc). Leia os consumos
desses carros, isto é, quantos quilômetros cada um desses carros faz com
um litro de combustível e armazene em outra lista. Calcule e mostre:
a) O modelo do carro mais econômico;
b) Quantos litros de combustível cada um dos carros cadastrados consome
para percorrer uma distância de 1000 quilômetros e quanto isto custará,
considerando um que a gasolina custe R$ 2,25 o litro. Abaixo segue uma tela
de exemplo. A disposição das informações deve ser o mais próximo possível
ao exemplo. Os dados são fictícios e podem mudar a cada execução do
programa.
"""

veiculos = []
consumos = []
preco = 2.25

for i in range(1, 6):
  veiculos.append(input("Veiculo %d" % i))
  consumos.append(float(input("Km por litro: ")))
menorConsumo = 0
print("Relatório Final")
for i in range(5):
  custo = 1000/consumos[i]
  gasto = custo * preco
  print("%i - %s - %.2f - %.1f litros - R$ %.2f" % (i+1, veiculos[i], consumos[i], custo, gasto))
  if consumos[i] > consumos[menorConsumo]:
    menorConsumo = i

print("O menor consumo é do %s"% veiculos[menorConsumo])

"""Prova Listas"""

#Questão01
num = input("Digite um número: ")
print(num[::-1])

#Questão02
data = input("Digite uma data no formato DD/MM/AAAA")
dia = int(data[0:2])
mes = int(data[3:5])
ano = int(data[6:])
if dia > 31 or mes > 12:
  print("Data inválida")
else:
  meses = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho",
           "agosto", "setembro", "outubro", "novembro", "dezembro"]
  mesExtenso = meses[mes-1]
  if mes == 4 or mes == 6 or mes == 9 or mes == 11 and dia > 30:
    print("Data inválida")
  elif mes == 2 and dia > 29:
    print("Data inválida")
  elif mes == 2 and dia > 28 and ano % 4 != 0:
    print("Data inválida")  
  else:
    print("%i de %s de %s" % (dia, mesExtenso, ano))

#Questão03
print("responda as perguntas com S (sim) ou N (não)")

perguntas = ["Você telefonou para a vítima?",
             "Você esteve no local do crime?",
             "Você mora perto da vítima?",
             "Você devia para a vítima?",
             "Você trabalhou para a vítima?",]
respostas = []
for pergunta in perguntas:
  respostas.append(input(pergunta).upper())

classificacao = respostas.count("S")

if classificacao < 2:
  print("Inocente")
elif classificacao == 2:
  print("Suspeito")
elif classificacao <= 4:
  print("Cumplice")
else:
  print("Assassino")

"""Pilha"""

livros = []
livros.append("O nome do vento")
livros.append("O temor do sábio")
livros.append("O guia do mochileiro das gálaxias")
livros.pop()
print(livros)

"""Fila"""

pessoas = []
pessoas.append("João")
pessoas.append("Zezinho")
pessoas.append("Maria")
pessoas.pop(0)
print(pessoas)
pessoas.insert(0, "fulana")

from collections import deque
fila = deque(["Eric", "John", "Michael"])
fila.append("Terry")
print(fila)
fila.appendleft("João")
print(fila)
fila.popleft()
print(fila)

"""Tupla"""

tupla =  (1,2,3,2)
print(tupla.index(3))
print(tupla.count(2))

"""Set"""

x = {"apple", "orange", "apple", "pear", "orange", "banana"}
print(x)
print("orange" in x)
print("grape" in x)
a = set('abracadabra')
b = set('alacazam')
print(a)
print(b)
print(a - b) #letras que estão em a mas não estão em b
print(a | b) #letras que estão em a ou b ou ambos
print(a & b) #letras que estão em a e b
print(a ^ b) #letras que estão em a ou b, mas não em ambos

"""Dict"""

pessoas = dict({952937834724: 'João', 957403757034: 'Pedro'})
print(pessoas.get(952937834724)) #retornar o valor da chave passada
print(pessoas[952937834724]) #retornar o valor da chave passada
pessoas[952937834724] = "José" #trocando o valor associado a uma chave
print(pessoas.get(952937834724))
pessoas.pop(952937834724) #deletando um par de chave e valor
print(pessoas)
pessoas[3854943870343] = "Maria" #adicionando um par de chave e valor
print(pessoas)
#nome = input("Digite o nome")
#pessoas[int(input("Digite o cpf"))] = nome
print(pessoas)
print(pessoas.keys()) #retornando o conjunto de chaves
print(pessoas.values()) #retornando o conjunto de valores

"""Atividade Extra = Resolução"""

#QUESTÃO 1
from collections import deque
escolha = 0
fila = deque([])
while True:
  print('''Menu
  1 - Qtd de carros na fila
  2 - Tempo de espera atual
  3 - Inserir um novo carro na fila
  4 - Remover um carro da fila
  0 - Sair''')
  escolha = int(input())
  placa = 0
  if escolha == 1:
    print("Há", len(fila), "carros na fila")
  elif escolha == 2:
    print("Tempo de espera atual é de", len(fila)*15, "minutos")
  elif escolha == 3:
    placa = int(input("Digite os ultimos 4 digitos da placa"))
    fila.append(placa)
  elif escolha == 4:
    fila.popleft()
    print("Veiculo removido")
  elif escolha == 0:
    break
  else:
    print("Opção inválida")

#QUESTÃO 2
lista = []

def empilhar(cadeira):
  if len(lista) == 0:
    pilha = []
    pilha.append(cadeira)
    lista.append(pilha)
  else:
    adicionado = False
    for i in lista:
      if i[0] == cadeira and len(i) < 10:
        i.append(cadeira)
        adicionado = True
        break
    if not adicionado:
      pilha2 = []
      pilha2.append(cadeira)
      lista.append(pilha2)
  return "Cadeira adicionada"

def desempilhar(cadeira):
  for i in lista:
    if i[0] == cadeira:
      i.pop()
      return "Cadeira removida"
  return "Não existe cadeira desse modelo"

def imprimir():
  for i in lista:
    print(i)

while True:
  print('''Menu
  1 - Adicionar uma cadeira
  2 - Remover uma cadeira
  3 - Ver Cadeiras
  0 - Sair''')
  escolha = int(input())
  if escolha == 1:
    cadeira = input("Digite o modelo da cadeira")
    print(empilhar(cadeira))
  elif escolha == 2:
    cadeira = input("Digite o modelo da cadeira")
    print(desempilhar(cadeira))
  elif escolha == 3:
    imprimir()
  elif escolha == 0:
    break
  else:
    print("Opção inválida")
